#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified or Edited by SSH SEDANG              #"
echo -e "#-----------------------------------------------#"
echo -e "# Terimakasih Kepada                            #"
echo -e "#-----------------------------------------------#"
echo -e "# Allah SWT                                     #"
echo -e "# SSH SEDANG                                    #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# Owner VPS                                     #"
echo -e "# VPNSTORES.NET                                 #"
echo -e "# GITHUB.COM                                    #"
echo -e "#-----------------------------------------------#"
echo -e "# Contact : sshsedang@gmail.com                 #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="